#!/usr/bin/env python3
"""Create a derived dataset after an approved image-placement disposition.

This utility never overwrites its candidates, queue, decisions, or media inputs.
``waived_unrecoverable_source`` is an administrative disposition, not a human
or machine review pass.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


EXCLUSION_CLASS = "definite_layout_error"
WAIVER_STATUS = "waived_unrecoverable_source"


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise ValueError(f"{path}:{line_number}: invalid JSONL") from exc
        if not isinstance(row, dict):
            raise ValueError(f"{path}:{line_number}: record must be an object")
        rows.append(row)
    return rows


def write_jsonl(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n" for row in rows),
                    encoding="utf-8")


def index_rows(rows: list[dict[str, Any]], label: str) -> dict[str, dict[str, Any]]:
    indexed: dict[str, dict[str, Any]] = {}
    for row in rows:
        post_id = row.get("post_id")
        if not isinstance(post_id, str) or not post_id:
            raise ValueError(f"{label}: missing post_id")
        if post_id in indexed:
            raise ValueError(f"{label}: duplicate post_id {post_id}")
        indexed[post_id] = row
    return indexed


def apply_disposition(candidates: list[dict[str, Any]], queue: list[dict[str, Any]],
                      decisions: list[dict[str, Any]], rule_report: dict[str, Any],
                      policy_id: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]],
                                                list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """Exclude structural failures and waive the remaining unrecoverable queue.

    Existing decisions are read only for audit accounting; they never affect the
    output.  A report must use the newer ``posts`` format generated by the P1
    rule-based image-placement audit.
    """
    if not policy_id.strip():
        raise ValueError("policy_id must be nonempty")
    candidate_by_id = index_rows(candidates, "candidates")
    queue_by_id = index_rows(queue, "review queue")
    decision_by_id = index_rows(decisions, "decisions")
    posts = rule_report.get("posts")
    if not isinstance(posts, list):
        raise ValueError("rule report must have a posts list")
    definite = index_rows([row for row in posts if row.get("classification") == EXCLUSION_CLASS],
                           "definite layout errors")
    missing_candidates = sorted(set(definite) - set(candidate_by_id))
    missing_queue = sorted(set(definite) - set(queue_by_id))
    if missing_candidates or missing_queue:
        raise ValueError("every definite layout error must be in both candidates and queue")
    invalid_decisions = sorted(set(decision_by_id) - set(queue_by_id))
    if invalid_decisions:
        raise ValueError("decision outside review queue")

    kept = [dict(row) for row in candidates if row["post_id"] not in definite]
    waived, exclusions, dispositions = [], [], []
    for row in queue:
        post_id = row["post_id"]
        decision_preserved = post_id in decision_by_id
        if post_id in definite:
            evidence = definite[post_id]
            exclusions.append({
                "post_id": post_id, "policy_id": policy_id,
                "disposition": "excluded_definite_layout_error",
                "rule_classification": EXCLUSION_CLASS,
                "rule_reasons": evidence.get("classification_reasons", []),
                "existing_human_decision_preserved_and_ignored": decision_preserved,
            })
            disposition = "excluded_definite_layout_error"
        else:
            output = dict(row)
            output.update({
                "llm_needs_review": False, "review_status": WAIVER_STATUS,
                "reviewer_id": None, "reviewed_at": None, "corrected_text": None,
                "corrected_media_order": None, "corrected_media_classification": None,
                "review_notes": "Project waiver: source unavailable; not a review result.",
            })
            waived.append(output)
            disposition = WAIVER_STATUS
        dispositions.append({
            "post_id": post_id, "policy_id": policy_id,
            "llm_needs_review_before": True, "llm_needs_review_after": False,
            "disposition": disposition, "human_review_performed": False,
            "existing_human_decision_preserved_and_ignored": decision_preserved,
        })

    index_rows(kept, "output candidates")
    index_rows(waived, "output queue")
    index_rows(exclusions, "exclusions")
    index_rows(dispositions, "dispositions")
    report = {
        "policy_id": policy_id, "input_candidate_records": len(candidates),
        "input_review_queue_records": len(queue), "input_human_decision_records": len(decisions),
        "human_decisions_used": 0, "human_decisions_preserved_but_ignored": len(decisions),
        "excluded_definite_layout_error_records": len(exclusions), "output_candidate_records": len(kept),
        "waived_unrecoverable_source_records": len(waived),
        "label_change": {"field": "llm_needs_review", "from": True, "to": False,
                         "meaning": "project waiver; not a human or machine review pass"},
    }
    return kept, waived, exclusions, dispositions, report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("candidates", type=Path)
    parser.add_argument("queue", type=Path)
    parser.add_argument("decisions", type=Path)
    parser.add_argument("rule_report", type=Path)
    parser.add_argument("--policy-id", required=True)
    parser.add_argument("--output-candidates", type=Path, required=True)
    parser.add_argument("--output-queue", type=Path, required=True)
    parser.add_argument("--exclusions", type=Path, required=True)
    parser.add_argument("--dispositions", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    result = apply_disposition(read_jsonl(args.candidates), read_jsonl(args.queue), read_jsonl(args.decisions),
                               json.loads(args.rule_report.read_text(encoding="utf-8")), args.policy_id)
    kept, waived, exclusions, dispositions, report = result
    write_jsonl(kept, args.output_candidates)
    write_jsonl(waived, args.output_queue)
    write_jsonl(exclusions, args.exclusions)
    write_jsonl(dispositions, args.dispositions)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
